name: Sample workflow
on:
 push:
   paths: 
     - '**.js'
jobs:
  build:
    name: JAI SRIRAM
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [mac-latest,ubuntu-latest,windows-latest]
        node: [10,12,14]
        exclude:
          - os: macos-latest
            node: 10
    steps:
      - uses: action/checkout@v2
      - name: uses node.js ${{matrix.node}}
      - uses: action/setup-node@v1
      - with:
          node-version: ${{matrix.node}}
      - run: npm ci
      - run: npm run  build--if-present
         
       
